---
- name: ensure elasticsearch storage dir
  file:
    dest: '{{ item }}'
    state: directory
    group: 1000
    mode: g+rwx
  with_items:
    - '{{ elasticsearch_data_dir }}'

- name: set sysctls on host
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - key: vm.max_map_count
      value: 262144

- name: run elasticsearch container
  docker_container:
    state: started
    restart: yes
    recreate: yes
    name: '{{ elasticsearch_container_name }}'
    image: '{{ elasticsearch_image }}'
    restart_policy: always
    hostname: '{{ elasticsearch_hostname }}'
    env: '{{ elasticsearch_env }}'
    published_ports: '{{ elasticsearch_published_ports }}'
    networks: '{{ elasticsearch_networks }}'
    volumes:
      - '{{ elasticsearch_data_dir }}:/usr/share/elasticsearch/data'
    ulimits: '{{ elasticsearch_ulimits }}'
    log_driver: '{{ elasticsearch_container_log_driver }}'
    log_opt: '{{ elasticsearch_container_log_opt }}'
