---
- name: ensure elasticsearch storage dir
  file:
    dest: '{{ item }}'
    state: directory
    group: 1000
    mode: g+rwx
  with_items:
    - '{{ elasticsearch_data_dir }}'

- name: set sysctls on host
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - key: vm.max_map_count
      value: 262144

- name: run elasticsearch container
  docker_container:
    state: started
    restart: yes
    recreate: yes
    name: '{{ elasticsearch_container_name }}'
    image: '{{ elasticsearch_image }}'
    restart_policy: always
    hostname: '{{ elasticsearch_hostname }}'
    env:
      ES_JAVA_OPTS: -Xms{{ elasticsearch_heap_size }} -Xmx{{ elasticsearch_heap_size }}
      TAKE_FILE_OWNERSHIP: true
      bootstrap.memory_lock: '{{ elasticsearch_bootstrap_memory_lock }}'
      cluster.name: '{{ elasticsearch_cluster_name }}'
      network.host: 0.0.0.0
      network.publish_host: '{{ elasticsearch_network_publish_host }}'
      transport.host: 0.0.0.0
      transport.publish_host: '{{ elasticsearch_transport_publish_host }}'
      transport.publish_port: '{{ elasticsearch_transport_publish_port }}'
      node.master: '{{ elasticsearch_node_master }}'
      node.data: '{{ elasticsearch_node_data }}'
      node.ingest: '{{ elasticsearch_node_ingest }}'
      node.name: '{{ elasticsearch_node_name }}'
      xpack.security.enabled: '{{ elasticsearch_xpack_security_enabled }}'
      discovery.type: '{{ elasticsearch_discovery_type }}'
      discovery.zen.minimum_master_nodes: '{{ elasticsearch_discovery_zen_minimum_master_nodes }}'
      discovery.zen.ping.unicast.hosts: '{{ elasticsearch_discovery_zen_ping_unicast_hosts }}'
      cluster.initial_master_nodes: '{{ elasticsearch_cluster_initial_master_nodes }}'
    published_ports: '{{ elasticsearch_published_ports }}'
    links: '{{ elasticsearch_links }}'
    networks: '{{ elasticsearch_networks }}'
    volumes:
      - '{{ elasticsearch_data_dir }}:/usr/share/elasticsearch/data'
    ulimits: '{{ elasticsearch_ulimits }}'
    log_driver: '{{ elasticsearch_container_log_driver }}'
    log_opt: '{{ elasticsearch_container_log_opt }}'
